theme = "github_dark"

[editor.cursor-shape]
insert = "bar"

[editor]
mouse = false
completion-trigger-len = 1
completion-timeout = 100
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "hint"
