theme = "github_dark"

[editor.cursor-shape]
insert = "bar"

[editor]
completion-trigger-len = 1
completion-timeout = 100
end-of-line-diagnostics = "hint"
true-color = true
cursorline = true
line-number = "relative"

[editor.inline-diagnostics]
cursor-line = "hint"
