#!/bin/bash

TEMPLATE_DIR="$HOME/dotfiles/scripts/cpp-templates"

# ask for project name
echo -n "Project name: "
read NAME
if [ -d "$NAME" ];
then
    echo "$NAME already exists!"
    exit 0
fi
mkdir $NAME

# ask for template
echo "Pick template:"
TEMPLATES=()
for i in $(ls -d "$TEMPLATE_DIR"/*/); do 
    TEMPLATES+=( $(basename ${i%%/}) )
done
PS3="> "
select OPTION in "${TEMPLATES[@]}"; do
    if [[ ! " ${TEMPLATES[*]} " =~ " ${OPTION} " ]]; then
        echo "Please select a valid option"
        exit 0
    fi
    break
done

cp -r "${TEMPLATE_DIR}/${OPTION}"/* "${NAME}/"
cd $NAME
sed -i "s/P_NAME/$NAME/" CMakeLists.txt
sed -i "s/P_NAME/$NAME/" run.sh

cmake -B build -G Ninja
